---
title: "Green space and ethnic background: simulation experiment"
output: html_notebook
---


```{r}
library(tidyverse)

library(ggbeeswarm)
library(ggpointdensity)

theme_set(theme_light())
```


```{r project_functions}
source("../R_code/green_space_functions.R")
```

```{r}
# read in data from excel
foe_green_space <- read_foe_data()

# focus on variables of interest
foe_green_space_focus <- foe_green_space %>% 
  select(msoa_code, msoa_name, green_space_deprivation_rating,
         total_pop_from_ethnicity_data, bame_pop,
         green_space_area_per_capita, pcnt_pop_with_go_space_access)

gardens <- read_ons_garden_data()

# focus on variables of interest
gardens_focus <- gardens %>% 
  
  # remove columns relating to house and flats, 
  # leaving columns relating to all households 
  # (i.e the total for both houses and flats)
  
  select(!(country_code:lad_name)) %>% 
  select(!(address_count_9:average_number_of_flats_sharing_a_garden)) %>% 
  rename(add_count = address_count_22,
         add_with_gar_count = adress_with_private_outdoor_space_count_23,
         total_gar_area = private_outdoor_space_total_area_m2_24,
         perc_add_with_gar = percentage_of_adresses_with_private_outdoor_space_25, 
         ave_gar_size = average_size_of_private_outdoor_space_m2_26)

# join green space and gardens datasets
gs_gardens <- foe_green_space_focus %>% 
  inner_join(gardens_focus)

# data cleaning
gs_gardens <- gs_gardens %>% 
  mutate(perc_pop_with_gs_access = pcnt_pop_with_go_space_access / 100,
         .keep = "unused") %>% 
  filter(ave_gar_size < 5000)
```
```{r}
simulate_msoa_pop <- function(pop, prop_bame_pop, perc_gar, perc_gs_access){
  tibble(bame = rbernoulli(pop, p = prop_bame_pop),
         garden = rbernoulli(pop, p = perc_gar),
         gs_access = rbernoulli(pop, p = perc_gs_access)
         )
}


gs_gardens_focus <- gs_gardens %>% 
  select(-msoa_name, -green_space_deprivation_rating,
         -add_count, -add_with_gar_count, -total_gar_area) %>% 
  mutate(prop_bame_pop = bame_pop / total_pop_from_ethnicity_data,
         .after = bame_pop)

# simulate a population
sim_pop <- gs_gardens_focus %>% 
  mutate(simulated_pop = pmap(list(total_pop_from_ethnicity_data, 
                                   prop_bame_pop,
                                   perc_add_with_gar,
                                   perc_pop_with_gs_access),
                               ~simulate_msoa_pop(..1, ..2, ..3, ..4))) %>% 
  unnest(simulated_pop)

# confirm summary stats for simulated population align with the actual data
sim_pop %>% 
  group_by(msoa_code) %>% 
  summarise(prop_bame = mean(bame),
            perc_gar = mean(garden),
            perc_gs_access = mean(gs_access)) %>% 
  left_join(gs_gardens_focus) %>% 
  mutate(bame_diff = prop_bame_pop - prop_bame,
         gar_diff = perc_add_with_gar - perc_gar,
         gs_diff = (perc_pop_with_gs_access) - perc_gs_access) %>% 
  summarise(across(ends_with("_diff"), mean))
```

```{r}

sample_sim_pop <- function(df, n = 10, strat_var = NULL){
  res <- df %>% 
    group_by({{strat_var}}) %>% 
    sample_n(n)
  
  return(res)
}

pre_process_for_log_scale <-  function(df, x, log_scale){

  df %>% 
    {if (log_scale) 
      mutate(., {{x}} := {{x}} + 1)
      else .}
}

add_log_scale_x <- function(log_scale){
  if (log_scale)
    scale_x_log10()
  else NULL
}

plot_gs_density <- function(df, x, log_scale = FALSE, ...){
  df %>%
    
    pre_process_for_log_scale({{x}}, log_scale) %>% 
    
    sample_sim_pop(...) %>% 
    
    ggplot(aes(x = {{x}},
               fill = bame)) +
    
    geom_density(alpha = 0.3) +
    
    add_log_scale_x(log_scale)
    
  
}

plot_gs_density(sim_pop, x = green_space_area_per_capita, log_scale = TRUE,
                n = 100000, strat_var = bame)

plot_gs_density(sim_pop, x = ave_gar_size, log_scale = TRUE,
                n = 100000, strat_var = bame)

plot_gs_density(sim_pop, x = perc_pop_with_gs_access, log_scale = FALSE,
                n = 100000, strat_var = bame)

plot_gs_density(sim_pop, x = perc_add_with_gar, log_scale = FALSE,
                n = 100000, strat_var = bame)


# 
# sample_sim_pop(sim_pop, n = 100000, strat_var = bame) %>% 


```

```{r}
gar_plot <- function(df, x, y, n, strat_var, ...){
  
  df %>% 
    
    sample_sim_pop(n, {{strat_var}}) %>%
    
    ggplot(aes({{x}}, {{y}} + 1)) +
    geom_pointdensity(alpha = 0.5) +  
    #geom_hex(aes(fill = ..ndensity..), colour = "grey50", bins = 50) + #aes(fill=..density..)
    scale_colour_viridis_c(option = "magma") +
    
    scale_y_log10() +
    
    facet_wrap(vars({{strat_var}}))
}



gar_plot(sim_pop %>% filter(perc_add_with_gar >= 0.5), 
         x = perc_add_with_gar, y = ave_gar_size, 
         strat_var = bame, n = 10000)

gar_plot(sim_pop, x = perc_pop_with_gs_access, y = green_space_area_per_capita, strat_var = bame, n = 10000)

  
```
```{r}
sim_pop %>%
  sample_n(10000) %>% 
  filter(green_space_area_per_capita < 5000) %>% 
  ggplot(aes(garden, green_space_area_per_capita + 1)) +
  geom_quasirandom(aes(colour = garden), alpha = 0.3) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) +
  scale_y_log10() +
  facet_wrap(~bame)

sim_pop %>%
  sample_n(10000) %>% 
  ggplot(aes(garden, pcnt_pop_with_go_space_access)) +
  geom_quasirandom(aes(colour = garden), alpha = 0.3) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) +
  facet_wrap(~bame)

```
```{r}
sim_pop %>%
  sample_n(10000) %>% 
  filter(green_space_area_per_capita < 5000) %>% 
  ggplot(aes(gs_access, ave_gar_size + 1)) +
  geom_quasirandom(aes(colour = gs_access), alpha = 0.3) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) +
  scale_y_log10() +
  facet_wrap(~ bame)

sim_pop %>%
  sample_n(10000) %>% 
  ggplot(aes(gs_access, perc_add_with_gar)) +
  geom_quasirandom(aes(colour = gs_access), alpha = 0.3) +
  geom_violin(alpha = 0.1, draw_quantiles = c(0.25, 0.5, 0.75)) +
  facet_wrap(~ bame)
```

```{r}
library(ggstatsplot)
gs_gardens_focus

fit <- lm(log(green_space_area_per_capita + 1) ~ log(ave_gar_size + 1) + total_pop_from_ethnicity_data, data = gs_gardens_focus)

ggcoefstats(fit)

ggcorrmat(gs_gardens_focus, colors = c("#B2182B", "white", "#4D4D4D"))


gs_gardens_focus <- gs_gardens_focus %>% 
  mutate(log_green_space_area_per_capita = log(green_space_area_per_capita + 1),
         log_ave_gar_size = log(ave_gar_size + 1))

ggscatterstats(gs_gardens_focus %>% filter(green_space_area_per_capita < 25000), 
               x = log_green_space_area_per_capita,
               y = log_ave_gar_size)


```

```{r}
library(GGally)

ggpairs(gs_gardens_focus %>% 
          select(-msoa_code) %>% 
          sample_n(1000),
        mapping = aes(alpha = 0.1),
        progress = FALSE)
```
```{r}
library(ggfortify)

fit <- lm(log(green_space_area_per_capita + 1) ~ log(ave_gar_size + 1), data = gs_gardens_focus)

autoplot(fit)

fit_1 <- rstanarm::stan_glm(log(green_space_area_per_capita + 1) ~ log(ave_gar_size + 1), data = gs_gardens_focus)

plot(fit)
plot(fit_1)

pca_res <- prcomp(gs_gardens_focus %>%
         select(-msoa_code)
         )

autoplot(pca_res)
```

